<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200501072203 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE mandataire');
        $this->addSql('DROP TABLE patrimoine');
        $this->addSql('DROP TABLE periode');
        $this->addSql('DROP TABLE prestationSociale');
        $this->addSql('DROP TABLE rapport');
        $this->addSql('DROP TABLE telephone');
        $this->addSql('ALTER TABLE noteDeFrais DROP INDEX noteDeFrais_FK, ADD UNIQUE INDEX UNIQ_B653342BF916DE3C (typeFraisId)');
        $this->addSql('ALTER TABLE noteDeFrais DROP FOREIGN KEY noteDeFrais_FK_1');
        $this->addSql('DROP INDEX notedefrais_fk_1 ON noteDeFrais');
        $this->addSql('CREATE INDEX IDX_B653342B64B64DCC ON noteDeFrais (userId)');
        $this->addSql('ALTER TABLE noteDeFrais ADD CONSTRAINT noteDeFrais_FK_1 FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE majeur DROP INDEX majeur_FK_contact, ADD UNIQUE INDEX UNIQ_573E60D5744BF426 (contactId)');
        $this->addSql('ALTER TABLE majeur DROP INDEX majeur_FK_parametremission, ADD UNIQUE INDEX UNIQ_573E60D590168DC (parametreMissionId)');
        $this->addSql('ALTER TABLE majeur DROP INDEX majeur_FK_jugement, ADD UNIQUE INDEX UNIQ_573E60D59A0645BD (jugementId)');
        $this->addSql('ALTER TABLE majeur DROP INDEX majeur_FK_adresse, ADD UNIQUE INDEX UNIQ_573E60D538FEBD48 (adresseId)');
        $this->addSql('DROP INDEX majeur_FK_1 ON majeur');
        $this->addSql('ALTER TABLE majeur DROP FOREIGN KEY majeur_FK_user');
        $this->addSql('DROP INDEX majeur_fk_user ON majeur');
        $this->addSql('CREATE INDEX IDX_573E60D564B64DCC ON majeur (userId)');
        $this->addSql('ALTER TABLE majeur ADD CONSTRAINT majeur_FK_user FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE familleCompte DROP FOREIGN KEY periode_FK_user');
        $this->addSql('DROP INDEX periode_fk ON familleCompte');
        $this->addSql('CREATE INDEX IDX_3922C51064B64DCC ON familleCompte (userId)');
        $this->addSql('ALTER TABLE familleCompte ADD CONSTRAINT periode_FK_user FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE typeOperation DROP FOREIGN KEY typeOperation_FK');
        $this->addSql('ALTER TABLE typeOperation ADD checkable TINYINT(1) NOT NULL');
        $this->addSql('DROP INDEX typeoperation_fk ON typeOperation');
        $this->addSql('CREATE INDEX IDX_784F465264B64DCC ON typeOperation (userId)');
        $this->addSql('ALTER TABLE typeOperation ADD CONSTRAINT typeOperation_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE importOperation DROP FOREIGN KEY importOperation_FK');
        $this->addSql('ALTER TABLE importOperation DROP FOREIGN KEY importOperation_FK_1');
        $this->addSql('ALTER TABLE importOperation DROP FOREIGN KEY importOperation_FK_2');
        $this->addSql('DROP INDEX importoperation_fk_1 ON importOperation');
        $this->addSql('CREATE INDEX IDX_1C1FDF5464B64DCC ON importOperation (userId)');
        $this->addSql('DROP INDEX importoperation_fk ON importOperation');
        $this->addSql('CREATE INDEX IDX_1C1FDF549B4044CE ON importOperation (majeurId)');
        $this->addSql('DROP INDEX importoperation_fk_2 ON importOperation');
        $this->addSql('CREATE INDEX IDX_1C1FDF543D8FE0CE ON importOperation (typeOperationId)');
        $this->addSql('ALTER TABLE importOperation ADD CONSTRAINT importOperation_FK FOREIGN KEY (majeurId) REFERENCES majeur (id)');
        $this->addSql('ALTER TABLE importOperation ADD CONSTRAINT importOperation_FK_1 FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE importOperation ADD CONSTRAINT importOperation_FK_2 FOREIGN KEY (typeOperationId) REFERENCES typeOperation (id)');
        $this->addSql('ALTER TABLE user DROP INDEX user_FK, ADD UNIQUE INDEX UNIQ_8D93D64938FEBD48 (adresseId)');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY user_FK_1');
        $this->addSql('ALTER TABLE user CHANGE roles roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('DROP INDEX email ON user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email)');
        $this->addSql('DROP INDEX user_fk_1 ON user');
        $this->addSql('CREATE INDEX IDX_8D93D649422C9DA3 ON user (groupeId)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT user_FK_1 FOREIGN KEY (groupeId) REFERENCES userGroupe (id)');
        $this->addSql('ALTER TABLE natureOperation DROP FOREIGN KEY natureOperation_FK');
        $this->addSql('DROP INDEX natureoperation_fk ON natureOperation');
        $this->addSql('CREATE INDEX IDX_4311C4BE64B64DCC ON natureOperation (userId)');
        $this->addSql('ALTER TABLE natureOperation ADD CONSTRAINT natureOperation_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE typeCompte DROP FOREIGN KEY typeCompte_FK');
        $this->addSql('ALTER TABLE typeCompte DROP FOREIGN KEY typeCompte_FK_1');
        $this->addSql('ALTER TABLE typeCompte CHANGE familleCompteId familleCompteId INT DEFAULT NULL');
        $this->addSql('DROP INDEX typecompte_fk ON typeCompte');
        $this->addSql('CREATE INDEX IDX_4C6E3C3D64B64DCC ON typeCompte (userId)');
        $this->addSql('DROP INDEX typecompte_fk_1 ON typeCompte');
        $this->addSql('CREATE INDEX IDX_4C6E3C3D8B715EBE ON typeCompte (familleCompteId)');
        $this->addSql('ALTER TABLE typeCompte ADD CONSTRAINT typeCompte_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE typeCompte ADD CONSTRAINT typeCompte_FK_1 FOREIGN KEY (familleCompteId) REFERENCES familleCompte (id)');
        $this->addSql('ALTER TABLE visite DROP FOREIGN KEY visite_FK');
        $this->addSql('ALTER TABLE visite DROP FOREIGN KEY visite_FK_1');
        $this->addSql('DROP INDEX visite_fk_1 ON visite');
        $this->addSql('CREATE INDEX IDX_B09C8CBB64B64DCC ON visite (userId)');
        $this->addSql('DROP INDEX visite_fk ON visite');
        $this->addSql('CREATE INDEX IDX_B09C8CBB9B4044CE ON visite (majeurId)');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT visite_FK FOREIGN KEY (majeurId) REFERENCES majeur (id)');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT visite_FK_1 FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE lieuVie DROP FOREIGN KEY lieuVie_FK');
        $this->addSql('DROP INDEX lieuvie_fk ON lieuVie');
        $this->addSql('CREATE INDEX IDX_126418D564B64DCC ON lieuVie (userId)');
        $this->addSql('ALTER TABLE lieuVie ADD CONSTRAINT lieuVie_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY contact_FK');
        $this->addSql('DROP INDEX periode_fk ON contact');
        $this->addSql('CREATE INDEX IDX_4C62E63864B64DCC ON contact (userId)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT contact_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE parametreMission DROP FOREIGN KEY parametreMission_FK');
        $this->addSql('ALTER TABLE parametreMission DROP FOREIGN KEY parametreMission_FK_1');
        $this->addSql('ALTER TABLE parametreMission DROP FOREIGN KEY parametreMission_FK_2');
        $this->addSql('ALTER TABLE parametreMission DROP FOREIGN KEY parametreMission_FK_6');
        $this->addSql('DROP INDEX parametremission_fk_6 ON parametreMission');
        $this->addSql('CREATE INDEX IDX_FC48315864B64DCC ON parametreMission (userId)');
        $this->addSql('DROP INDEX parametremission_fk_1 ON parametreMission');
        $this->addSql('CREATE INDEX IDX_FC483158C84D3A08 ON parametreMission (natureId)');
        $this->addSql('DROP INDEX parametremission_fk ON parametreMission');
        $this->addSql('CREATE INDEX IDX_FC48315818DE93B3 ON parametreMission (protectionId)');
        $this->addSql('DROP INDEX parametremission_fk_2 ON parametreMission');
        $this->addSql('CREATE INDEX IDX_FC483158C59EF89A ON parametreMission (lieuVieId)');
        $this->addSql('ALTER TABLE parametreMission ADD CONSTRAINT parametreMission_FK FOREIGN KEY (protectionId) REFERENCES protection (id)');
        $this->addSql('ALTER TABLE parametreMission ADD CONSTRAINT parametreMission_FK_1 FOREIGN KEY (natureId) REFERENCES nature (id)');
        $this->addSql('ALTER TABLE parametreMission ADD CONSTRAINT parametreMission_FK_2 FOREIGN KEY (lieuVieId) REFERENCES lieuVie (id)');
        $this->addSql('ALTER TABLE parametreMission ADD CONSTRAINT parametreMission_FK_6 FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE donneeBancaire DROP INDEX donneeBancaire_FK_1, ADD UNIQUE INDEX UNIQ_C1EA70753D25F10B (agenceBancaireId)');
        $this->addSql('ALTER TABLE donneeBancaire DROP INDEX donneeBancaire_FK_2, ADD UNIQUE INDEX UNIQ_C1EA70756F3A3BA5 (typeCompteId)');
        $this->addSql('ALTER TABLE donneeBancaire DROP FOREIGN KEY donneeBancaire_FK');
        $this->addSql('ALTER TABLE donneeBancaire DROP FOREIGN KEY donneeBancaire_FK_3');
        $this->addSql('ALTER TABLE donneeBancaire CHANGE soldeCourant soldeCourant DOUBLE PRECISION NOT NULL, CHANGE soldePrecedent soldePrecedent DOUBLE PRECISION NOT NULL');
        $this->addSql('DROP INDEX donneebancaire_fk_3 ON donneeBancaire');
        $this->addSql('CREATE INDEX IDX_C1EA707564B64DCC ON donneeBancaire (userId)');
        $this->addSql('DROP INDEX donneebancaire_fk ON donneeBancaire');
        $this->addSql('CREATE INDEX IDX_C1EA70759B4044CE ON donneeBancaire (majeurId)');
        $this->addSql('ALTER TABLE donneeBancaire ADD CONSTRAINT donneeBancaire_FK FOREIGN KEY (majeurId) REFERENCES majeur (id)');
        $this->addSql('ALTER TABLE donneeBancaire ADD CONSTRAINT donneeBancaire_FK_3 FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE adresse DROP FOREIGN KEY adresse_FK');
        $this->addSql('DROP INDEX adresse_fk ON adresse');
        $this->addSql('CREATE INDEX IDX_C35F081664B64DCC ON adresse (userId)');
        $this->addSql('ALTER TABLE adresse ADD CONSTRAINT adresse_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE jugement DROP FOREIGN KEY banque_FK_copy');
        $this->addSql('ALTER TABLE jugement DROP FOREIGN KEY jugement_FK_tribunal');
        $this->addSql('DROP INDEX banque_fk ON jugement');
        $this->addSql('CREATE INDEX IDX_F53C8E5064B64DCC ON jugement (userId)');
        $this->addSql('DROP INDEX jugement_fk_tribunal ON jugement');
        $this->addSql('CREATE INDEX IDX_F53C8E50C52EE6EA ON jugement (tribunalId)');
        $this->addSql('ALTER TABLE jugement ADD CONSTRAINT banque_FK_copy FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE jugement ADD CONSTRAINT jugement_FK_tribunal FOREIGN KEY (tribunalId) REFERENCES tribunal (id)');
        $this->addSql('ALTER TABLE protection DROP FOREIGN KEY protection_FK');
        $this->addSql('DROP INDEX protection_fk ON protection');
        $this->addSql('CREATE INDEX IDX_B7E52FB564B64DCC ON protection (userId)');
        $this->addSql('ALTER TABLE protection ADD CONSTRAINT protection_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE userGroupe DROP FOREIGN KEY periode_FK_user_groupe');
        $this->addSql('DROP INDEX periode_fk ON userGroupe');
        $this->addSql('CREATE INDEX IDX_6BEF9ED364B64DCC ON userGroupe (userId)');
        $this->addSql('ALTER TABLE userGroupe ADD CONSTRAINT periode_FK_user_groupe FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE typeFrais DROP FOREIGN KEY typeFrais_FK');
        $this->addSql('DROP INDEX typefrais_fk ON typeFrais');
        $this->addSql('CREATE INDEX IDX_6EABD68F64B64DCC ON typeFrais (userId)');
        $this->addSql('ALTER TABLE typeFrais ADD CONSTRAINT typeFrais_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE agenceBancaire DROP FOREIGN KEY banque_FK');
        $this->addSql('DROP INDEX banque_fk ON agenceBancaire');
        $this->addSql('CREATE INDEX IDX_63C6193C64B64DCC ON agenceBancaire (userId)');
        $this->addSql('ALTER TABLE agenceBancaire ADD CONSTRAINT banque_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE tribunal DROP FOREIGN KEY tribunal_FK');
        $this->addSql('DROP INDEX tribunal_fk ON tribunal');
        $this->addSql('CREATE INDEX IDX_DC8C3AAF64B64DCC ON tribunal (userId)');
        $this->addSql('ALTER TABLE tribunal ADD CONSTRAINT tribunal_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE nature DROP FOREIGN KEY nature_FK');
        $this->addSql('DROP INDEX nature_fk ON nature');
        $this->addSql('CREATE INDEX IDX_B1D882A764B64DCC ON nature (userId)');
        $this->addSql('ALTER TABLE nature ADD CONSTRAINT nature_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE compteGestion DROP FOREIGN KEY compteGestion_FK_1');
        $this->addSql('ALTER TABLE compteGestion DROP FOREIGN KEY compteGestion_FK_2');
        $this->addSql('ALTER TABLE compteGestion DROP FOREIGN KEY compteGestion_FK_3');
        $this->addSql('DROP INDEX comptegestion_fk_2 ON compteGestion');
        $this->addSql('CREATE INDEX IDX_3215D29864B64DCC ON compteGestion (userId)');
        $this->addSql('DROP INDEX comptegestion_fk_1 ON compteGestion');
        $this->addSql('CREATE INDEX IDX_3215D2983D8FE0CE ON compteGestion (typeOperationId)');
        $this->addSql('DROP INDEX comptegestion_fk_3 ON compteGestion');
        $this->addSql('CREATE INDEX IDX_3215D29828F07E97 ON compteGestion (donneeBancaireId)');
        $this->addSql('ALTER TABLE compteGestion ADD CONSTRAINT compteGestion_FK_1 FOREIGN KEY (typeOperationId) REFERENCES typeOperation (id)');
        $this->addSql('ALTER TABLE compteGestion ADD CONSTRAINT compteGestion_FK_2 FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE compteGestion ADD CONSTRAINT compteGestion_FK_3 FOREIGN KEY (donneeBancaireId) REFERENCES donneeBancaire (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE mandataire (id INT AUTO_INCREMENT NOT NULL, userId INT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prenom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, adresseId INT NOT NULL, dateCreation DATETIME NOT NULL, dateModification DATETIME NOT NULL, INDEX mandataire_FK (adresseId), INDEX mandataire_FK_1 (userId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE patrimoine (id INT AUTO_INCREMENT NOT NULL, majeurId INT NOT NULL, INDEX rapport_FK (majeurId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE periode (id INT AUTO_INCREMENT NOT NULL, userId INT NOT NULL, libelle VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, dateCreation DATETIME NOT NULL, dateModification DATETIME NOT NULL, INDEX periode_FK (userId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE prestationSociale (id INT AUTO_INCREMENT NOT NULL, userId INT NOT NULL, libelle VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, dateCreation DATETIME NOT NULL, dateModification DATETIME NOT NULL, INDEX prestationSociale_FK (userId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rapport (id INT AUTO_INCREMENT NOT NULL, majeurId INT NOT NULL, annee INT NOT NULL, commentaire TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX rapport_FK (majeurId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE telephone (id INT AUTO_INCREMENT NOT NULL, userId INT NOT NULL, libelle VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, dateCreation DATETIME NOT NULL, dateModification DATETIME NOT NULL, INDEX periode_FK (userId), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE mandataire ADD CONSTRAINT mandataire_FK FOREIGN KEY (adresseId) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE mandataire ADD CONSTRAINT mandataire_FK_1 FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE patrimoine ADD CONSTRAINT rapport_FK_copy FOREIGN KEY (majeurId) REFERENCES majeur (id)');
        $this->addSql('ALTER TABLE periode ADD CONSTRAINT periode_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE prestationSociale ADD CONSTRAINT prestationSociale_FK FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE rapport ADD CONSTRAINT rapport_FK FOREIGN KEY (majeurId) REFERENCES majeur (id)');
        $this->addSql('ALTER TABLE telephone ADD CONSTRAINT periode_FK_copy FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE adresse DROP FOREIGN KEY FK_C35F081664B64DCC');
        $this->addSql('DROP INDEX idx_c35f081664b64dcc ON adresse');
        $this->addSql('CREATE INDEX adresse_FK ON adresse (userId)');
        $this->addSql('ALTER TABLE adresse ADD CONSTRAINT FK_C35F081664B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE agenceBancaire DROP FOREIGN KEY FK_63C6193C64B64DCC');
        $this->addSql('DROP INDEX idx_63c6193c64b64dcc ON agenceBancaire');
        $this->addSql('CREATE INDEX banque_FK ON agenceBancaire (userId)');
        $this->addSql('ALTER TABLE agenceBancaire ADD CONSTRAINT FK_63C6193C64B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE compteGestion DROP FOREIGN KEY FK_3215D29864B64DCC');
        $this->addSql('ALTER TABLE compteGestion DROP FOREIGN KEY FK_3215D2983D8FE0CE');
        $this->addSql('ALTER TABLE compteGestion DROP FOREIGN KEY FK_3215D29828F07E97');
        $this->addSql('DROP INDEX idx_3215d29828f07e97 ON compteGestion');
        $this->addSql('CREATE INDEX compteGestion_FK_3 ON compteGestion (donneeBancaireId)');
        $this->addSql('DROP INDEX idx_3215d2983d8fe0ce ON compteGestion');
        $this->addSql('CREATE INDEX compteGestion_FK_1 ON compteGestion (typeOperationId)');
        $this->addSql('DROP INDEX idx_3215d29864b64dcc ON compteGestion');
        $this->addSql('CREATE INDEX compteGestion_FK_2 ON compteGestion (userId)');
        $this->addSql('ALTER TABLE compteGestion ADD CONSTRAINT FK_3215D29864B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE compteGestion ADD CONSTRAINT FK_3215D2983D8FE0CE FOREIGN KEY (typeOperationId) REFERENCES typeOperation (id)');
        $this->addSql('ALTER TABLE compteGestion ADD CONSTRAINT FK_3215D29828F07E97 FOREIGN KEY (donneeBancaireId) REFERENCES donneeBancaire (id)');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E63864B64DCC');
        $this->addSql('DROP INDEX idx_4c62e63864b64dcc ON contact');
        $this->addSql('CREATE INDEX periode_FK ON contact (userId)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E63864B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE donneeBancaire DROP INDEX UNIQ_C1EA70753D25F10B, ADD INDEX donneeBancaire_FK_1 (agenceBancaireId)');
        $this->addSql('ALTER TABLE donneeBancaire DROP INDEX UNIQ_C1EA70756F3A3BA5, ADD INDEX donneeBancaire_FK_2 (typeCompteId)');
        $this->addSql('ALTER TABLE donneeBancaire DROP FOREIGN KEY FK_C1EA707564B64DCC');
        $this->addSql('ALTER TABLE donneeBancaire DROP FOREIGN KEY FK_C1EA70759B4044CE');
        $this->addSql('ALTER TABLE donneeBancaire CHANGE soldeCourant soldeCourant DOUBLE PRECISION DEFAULT \'0\', CHANGE soldePrecedent soldePrecedent DOUBLE PRECISION DEFAULT \'0\'');
        $this->addSql('DROP INDEX idx_c1ea70759b4044ce ON donneeBancaire');
        $this->addSql('CREATE INDEX donneeBancaire_FK ON donneeBancaire (majeurId)');
        $this->addSql('DROP INDEX idx_c1ea707564b64dcc ON donneeBancaire');
        $this->addSql('CREATE INDEX donneeBancaire_FK_3 ON donneeBancaire (userId)');
        $this->addSql('ALTER TABLE donneeBancaire ADD CONSTRAINT FK_C1EA707564B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE donneeBancaire ADD CONSTRAINT FK_C1EA70759B4044CE FOREIGN KEY (majeurId) REFERENCES majeur (id)');
        $this->addSql('ALTER TABLE familleCompte DROP FOREIGN KEY FK_3922C51064B64DCC');
        $this->addSql('DROP INDEX idx_3922c51064b64dcc ON familleCompte');
        $this->addSql('CREATE INDEX periode_FK ON familleCompte (userId)');
        $this->addSql('ALTER TABLE familleCompte ADD CONSTRAINT FK_3922C51064B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE importOperation DROP FOREIGN KEY FK_1C1FDF5464B64DCC');
        $this->addSql('ALTER TABLE importOperation DROP FOREIGN KEY FK_1C1FDF549B4044CE');
        $this->addSql('ALTER TABLE importOperation DROP FOREIGN KEY FK_1C1FDF543D8FE0CE');
        $this->addSql('DROP INDEX idx_1c1fdf543d8fe0ce ON importOperation');
        $this->addSql('CREATE INDEX importOperation_FK_2 ON importOperation (typeOperationId)');
        $this->addSql('DROP INDEX idx_1c1fdf549b4044ce ON importOperation');
        $this->addSql('CREATE INDEX importOperation_FK ON importOperation (majeurId)');
        $this->addSql('DROP INDEX idx_1c1fdf5464b64dcc ON importOperation');
        $this->addSql('CREATE INDEX importOperation_FK_1 ON importOperation (userId)');
        $this->addSql('ALTER TABLE importOperation ADD CONSTRAINT FK_1C1FDF5464B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE importOperation ADD CONSTRAINT FK_1C1FDF549B4044CE FOREIGN KEY (majeurId) REFERENCES majeur (id)');
        $this->addSql('ALTER TABLE importOperation ADD CONSTRAINT FK_1C1FDF543D8FE0CE FOREIGN KEY (typeOperationId) REFERENCES typeOperation (id)');
        $this->addSql('ALTER TABLE jugement DROP FOREIGN KEY FK_F53C8E5064B64DCC');
        $this->addSql('ALTER TABLE jugement DROP FOREIGN KEY FK_F53C8E50C52EE6EA');
        $this->addSql('DROP INDEX idx_f53c8e5064b64dcc ON jugement');
        $this->addSql('CREATE INDEX banque_FK ON jugement (userId)');
        $this->addSql('DROP INDEX idx_f53c8e50c52ee6ea ON jugement');
        $this->addSql('CREATE INDEX jugement_FK_tribunal ON jugement (tribunalId)');
        $this->addSql('ALTER TABLE jugement ADD CONSTRAINT FK_F53C8E5064B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE jugement ADD CONSTRAINT FK_F53C8E50C52EE6EA FOREIGN KEY (tribunalId) REFERENCES tribunal (id)');
        $this->addSql('ALTER TABLE lieuVie DROP FOREIGN KEY FK_126418D564B64DCC');
        $this->addSql('DROP INDEX idx_126418d564b64dcc ON lieuVie');
        $this->addSql('CREATE INDEX lieuVie_FK ON lieuVie (userId)');
        $this->addSql('ALTER TABLE lieuVie ADD CONSTRAINT FK_126418D564B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE majeur DROP INDEX UNIQ_573E60D538FEBD48, ADD INDEX majeur_FK_adresse (adresseId)');
        $this->addSql('ALTER TABLE majeur DROP INDEX UNIQ_573E60D59A0645BD, ADD INDEX majeur_FK_jugement (jugementId)');
        $this->addSql('ALTER TABLE majeur DROP INDEX UNIQ_573E60D5744BF426, ADD INDEX majeur_FK_contact (contactId)');
        $this->addSql('ALTER TABLE majeur DROP INDEX UNIQ_573E60D590168DC, ADD INDEX majeur_FK_parametremission (parametreMissionId)');
        $this->addSql('ALTER TABLE majeur DROP FOREIGN KEY FK_573E60D564B64DCC');
        $this->addSql('CREATE INDEX majeur_FK_1 ON majeur (civilite)');
        $this->addSql('DROP INDEX idx_573e60d564b64dcc ON majeur');
        $this->addSql('CREATE INDEX majeur_FK_user ON majeur (userId)');
        $this->addSql('ALTER TABLE majeur ADD CONSTRAINT FK_573E60D564B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE nature DROP FOREIGN KEY FK_B1D882A764B64DCC');
        $this->addSql('DROP INDEX idx_b1d882a764b64dcc ON nature');
        $this->addSql('CREATE INDEX nature_FK ON nature (userId)');
        $this->addSql('ALTER TABLE nature ADD CONSTRAINT FK_B1D882A764B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE natureOperation DROP FOREIGN KEY FK_4311C4BE64B64DCC');
        $this->addSql('DROP INDEX idx_4311c4be64b64dcc ON natureOperation');
        $this->addSql('CREATE INDEX natureOperation_FK ON natureOperation (userId)');
        $this->addSql('ALTER TABLE natureOperation ADD CONSTRAINT FK_4311C4BE64B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE noteDeFrais DROP INDEX UNIQ_B653342BF916DE3C, ADD INDEX noteDeFrais_FK (typeFraisId)');
        $this->addSql('ALTER TABLE noteDeFrais DROP FOREIGN KEY FK_B653342B64B64DCC');
        $this->addSql('DROP INDEX idx_b653342b64b64dcc ON noteDeFrais');
        $this->addSql('CREATE INDEX noteDeFrais_FK_1 ON noteDeFrais (userId)');
        $this->addSql('ALTER TABLE noteDeFrais ADD CONSTRAINT FK_B653342B64B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE parametreMission DROP FOREIGN KEY FK_FC48315864B64DCC');
        $this->addSql('ALTER TABLE parametreMission DROP FOREIGN KEY FK_FC483158C84D3A08');
        $this->addSql('ALTER TABLE parametreMission DROP FOREIGN KEY FK_FC48315818DE93B3');
        $this->addSql('ALTER TABLE parametreMission DROP FOREIGN KEY FK_FC483158C59EF89A');
        $this->addSql('DROP INDEX idx_fc483158c59ef89a ON parametreMission');
        $this->addSql('CREATE INDEX parametreMission_FK_2 ON parametreMission (lieuVieId)');
        $this->addSql('DROP INDEX idx_fc48315864b64dcc ON parametreMission');
        $this->addSql('CREATE INDEX parametreMission_FK_6 ON parametreMission (userId)');
        $this->addSql('DROP INDEX idx_fc483158c84d3a08 ON parametreMission');
        $this->addSql('CREATE INDEX parametreMission_FK_1 ON parametreMission (natureId)');
        $this->addSql('DROP INDEX idx_fc48315818de93b3 ON parametreMission');
        $this->addSql('CREATE INDEX parametreMission_FK ON parametreMission (protectionId)');
        $this->addSql('ALTER TABLE parametreMission ADD CONSTRAINT FK_FC48315864B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE parametreMission ADD CONSTRAINT FK_FC483158C84D3A08 FOREIGN KEY (natureId) REFERENCES nature (id)');
        $this->addSql('ALTER TABLE parametreMission ADD CONSTRAINT FK_FC48315818DE93B3 FOREIGN KEY (protectionId) REFERENCES protection (id)');
        $this->addSql('ALTER TABLE parametreMission ADD CONSTRAINT FK_FC483158C59EF89A FOREIGN KEY (lieuVieId) REFERENCES lieuVie (id)');
        $this->addSql('ALTER TABLE protection DROP FOREIGN KEY FK_B7E52FB564B64DCC');
        $this->addSql('DROP INDEX idx_b7e52fb564b64dcc ON protection');
        $this->addSql('CREATE INDEX protection_FK ON protection (userId)');
        $this->addSql('ALTER TABLE protection ADD CONSTRAINT FK_B7E52FB564B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE tribunal DROP FOREIGN KEY FK_DC8C3AAF64B64DCC');
        $this->addSql('DROP INDEX idx_dc8c3aaf64b64dcc ON tribunal');
        $this->addSql('CREATE INDEX tribunal_FK ON tribunal (userId)');
        $this->addSql('ALTER TABLE tribunal ADD CONSTRAINT FK_DC8C3AAF64B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE typeCompte DROP FOREIGN KEY FK_4C6E3C3D64B64DCC');
        $this->addSql('ALTER TABLE typeCompte DROP FOREIGN KEY FK_4C6E3C3D8B715EBE');
        $this->addSql('ALTER TABLE typeCompte CHANGE familleCompteId familleCompteId INT NOT NULL');
        $this->addSql('DROP INDEX idx_4c6e3c3d8b715ebe ON typeCompte');
        $this->addSql('CREATE INDEX typeCompte_FK_1 ON typeCompte (familleCompteId)');
        $this->addSql('DROP INDEX idx_4c6e3c3d64b64dcc ON typeCompte');
        $this->addSql('CREATE INDEX typeCompte_FK ON typeCompte (userId)');
        $this->addSql('ALTER TABLE typeCompte ADD CONSTRAINT FK_4C6E3C3D64B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE typeCompte ADD CONSTRAINT FK_4C6E3C3D8B715EBE FOREIGN KEY (familleCompteId) REFERENCES familleCompte (id)');
        $this->addSql('ALTER TABLE typeFrais DROP FOREIGN KEY FK_6EABD68F64B64DCC');
        $this->addSql('DROP INDEX idx_6eabd68f64b64dcc ON typeFrais');
        $this->addSql('CREATE INDEX typeFrais_FK ON typeFrais (userId)');
        $this->addSql('ALTER TABLE typeFrais ADD CONSTRAINT FK_6EABD68F64B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE typeOperation DROP FOREIGN KEY FK_784F465264B64DCC');
        $this->addSql('ALTER TABLE typeOperation DROP checkable');
        $this->addSql('DROP INDEX idx_784f465264b64dcc ON typeOperation');
        $this->addSql('CREATE INDEX typeOperation_FK ON typeOperation (userId)');
        $this->addSql('ALTER TABLE typeOperation ADD CONSTRAINT FK_784F465264B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user DROP INDEX UNIQ_8D93D64938FEBD48, ADD INDEX user_FK (adresseId)');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649422C9DA3');
        $this->addSql('ALTER TABLE user CHANGE roles roles VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('DROP INDEX uniq_8d93d649e7927c74 ON user');
        $this->addSql('CREATE UNIQUE INDEX email ON user (email)');
        $this->addSql('DROP INDEX idx_8d93d649422c9da3 ON user');
        $this->addSql('CREATE INDEX user_FK_1 ON user (groupeId)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649422C9DA3 FOREIGN KEY (groupeId) REFERENCES userGroupe (id)');
        $this->addSql('ALTER TABLE userGroupe DROP FOREIGN KEY FK_6BEF9ED364B64DCC');
        $this->addSql('DROP INDEX idx_6bef9ed364b64dcc ON userGroupe');
        $this->addSql('CREATE INDEX periode_FK ON userGroupe (userId)');
        $this->addSql('ALTER TABLE userGroupe ADD CONSTRAINT FK_6BEF9ED364B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE visite DROP FOREIGN KEY FK_B09C8CBB64B64DCC');
        $this->addSql('ALTER TABLE visite DROP FOREIGN KEY FK_B09C8CBB9B4044CE');
        $this->addSql('DROP INDEX idx_b09c8cbb9b4044ce ON visite');
        $this->addSql('CREATE INDEX visite_FK ON visite (majeurId)');
        $this->addSql('DROP INDEX idx_b09c8cbb64b64dcc ON visite');
        $this->addSql('CREATE INDEX visite_FK_1 ON visite (userId)');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBB64B64DCC FOREIGN KEY (userId) REFERENCES user (id)');
        $this->addSql('ALTER TABLE visite ADD CONSTRAINT FK_B09C8CBB9B4044CE FOREIGN KEY (majeurId) REFERENCES majeur (id)');
    }
}
